FROM debian:stable

WORKDIR /root/quicklisp/local-projects/cl-avro/test

COPY cl-avro.asd version.lisp ../
COPY src ../src
COPY test ./

RUN apt-get update && apt-get install -y --no-install-recommends \
    sbcl cl-quicklisp \
    && sbcl --noinform --end-runtime-options \
            --no-sysinit --no-userinit \
            --load $(find / -name 'quicklisp.lisp' -type f) \
            --non-interactive \
            --eval '(quicklisp-quickstart:install)' \
            --eval '(ql:quickload :cl-avro/test)' \
            --eval '(sb-ext:save-lisp-and-die \
                      "test-image" \
                      :toplevel (lambda () \
                                  (asdf:perform :test-op :cl-avro/test)))' \
            --end-toplevel-options \
    && mkdir /app \
    && mv ./test-image /app/test-image

CMD ["sbcl", "--noinform", "--core", "/app/test-image"]
