version: 2

jobs:
  test:
    working_directory: ~/cl-avro

    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build . -f ./test/Dockerfile.test -t cl-avro:v1
          docker run -it --rm cl-avro:v1

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
